---
title: "BSV 2025 - Boxplot von Brandopfern"
author: "Mirco Heidemann"
date: " Mai 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RColorBrewer)
library(kableExtra)
library(reshape2)

## relative pfade
data_pth = '../Data/'

## --- Save the ggplot's
width_plot = 12
# height_plot = (3/4) * width_plot
height_plot = (9/16) * width_plot
```

##### Daten zu Brandopfer laden: Import und wrangling
```{r message = FALSE, cache=TRUE}
input_csv <- paste0(data_pth, 'gvz_schaeden_mit_brandopfern_201812.csv')

dat_brand <- read_delim(input_csv, delim = ";", col_names = TRUE,
                        locale = locale(encoding = 'ISO-8859-1'),
                                         col_types = cols(
                   SchadenSumme = col_number(),
                   SchadenDatum = col_date(format = "%d.%m.%Y"))) %>% 
  filter(str_detect(SchadenArtBezeichnung, 'Feuer'),
         Ausdr3 < 2018) %>% 
  mutate(schadencode = as.integer(str_extract(CodTextDt, "[[:digit:]]+"))) %>% 
  rename(verletzte = SchadenVerletzte,
         todesopfer = SchadenTodesopfer)
```

#### Laszlo's Zweckcode Kategorien
```{r}
dat <- dat_brand %>% 
  mutate(zwkcd_kat = case_when(
    floor(GebaeudeZweckCode/1e3) == 2 ~ "wohnen",
    floor(GebaeudeZweckCode/1e2) == 10 ~ "verwaltung",
    floor(GebaeudeZweckCode/1e2) == 11 ~ "verwaltung",
    floor(GebaeudeZweckCode/1e2) == 12 ~ "verwaltung",
    floor(GebaeudeZweckCode/1e2) == 13 ~ "spital",
    floor(GebaeudeZweckCode/1e2) == 14 ~ "heim",
    floor(GebaeudeZweckCode/1e2) == 15 ~ "verwaltung",
    floor(GebaeudeZweckCode/1e2) == 16 ~ "verwaltung",
    floor(GebaeudeZweckCode/1e2) == 17 ~ "verwaltung",
    floor(GebaeudeZweckCode/1e2) == 18 ~ "verwaltung",
    floor(GebaeudeZweckCode/1e2) == 19 ~ "verwaltung",
    floor(GebaeudeZweckCode/1e3) == 3 ~ "landwirtschaft",
    floor(GebaeudeZweckCode/1e3) == 4 ~ "industrie",
    floor(GebaeudeZweckCode/1e3) == 6 ~ "industrie",
    floor(GebaeudeZweckCode/1e3) == 7 ~ "industrie",
    floor(GebaeudeZweckCode/1e2) == 50 ~ "handel",
    floor(GebaeudeZweckCode/1e2) == 51 ~ "lager",
    floor(GebaeudeZweckCode/1e2) == 55 ~ "handel",
    floor(GebaeudeZweckCode/1e2) == 80 ~ "hotel",
    floor(GebaeudeZweckCode/1e2) == 81 ~ "gastwirtschaft",
    floor(GebaeudeZweckCode/1e3) == 9 ~ "nebengebäude"))
```

#### Welche Opfer wären durch einen baulichen oder technischen Brandschutz zu verhindern?
Berücksichtige nur Daten mit Todesopfern
!! MIT LASZLO ABZUSTIMMEN!!
```{r}
dat <- dat %>% 
  filter(todesopfer > 0) %>% 
  mutate(tod_verhinderbar = ifelse(schadencode %in% c(11, 12, 13, 14, 15, 16, 19, 61, 81, 82),
                                   "ja", "nein"))
```

#### Boxplots pro Zweck Kategorie
```{r message = FALSE}
library("ggpubr")

# Add p-values comparing groups: Specify the required comparisons
my_comparisons <- list(c("nein", "ja"))

# Nur für die Kategorie Wohnen sind genügend Daten vorhanden um einen Boxplot zu erstellen
dat_select <- dat %>% 
  filter(zwkcd_kat == "wohnen")

ggboxplot(dat_select, x = "tod_verhinderbar", y = "todesopfer",
          color = "tod_verhinderbar",
          add = "jitter",
          # title ="Zweckcode Kategorie Wohnen",
          palette =c("#00AFBB", "#E7B800")) +
  # Add pairwise comparisons p-value
  stat_compare_means(comparisons = my_comparisons)
```

